version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellyfin_server_1
      APP_PORT: 7097
      PROXY_AUTH_ADD: "false"
  
  server:
    image: ghcr.io/endrl/jellyfin-vue:latest
    container_name: jellyfin-vue
    environment:
      - DEFAULT_SERVERS=jellyfin_media-server_1
    ports:
      - 7097:80
    restart: unless-stopped
    media-server:
    # Patched jellyfin image which supports the media analyzer
      image: ghcr.io/endrl/jellyfin:latest
      restart: on-failure
      hostname: "${DEVICE_HOSTNAME}"
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - ${APP_DATA_DIR}/data/config:/config
        - ${UMBREL_ROOT}/data/storage/media:/media
      ports:
          # Service auto-discovery
        - 7359:7359/udp
        - 8096:8096
### Jellyfin Segment Editor - Media Segments management made easy
### Also available as tiny app for your desktop
### Project: https://github.com/endrl/segment-editor#jellyfin-segment-editor
    jellyfin-se:
      image: ghcr.io/endrl/jellyfin-se:latest
      container_name: jellyfin-se
      ports:
        - 7098:80
      restart: unless-stopped