version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellyfin_vue_server_1
      APP_PORT: 7097
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/endrl/jellyfin-vue:latest
    container_name: jellyfin-vue
    ports:
      - 7097:80
    restart: unless-stopped
### Jellyfin Segment Editor - Media Segments management made easy
### Also available as tiny app for your desktop
### Project: https://github.com/endrl/segment-editor#jellyfin-segment-editor
  jellyfin-se:
    image: ghcr.io/endrl/jellyfin-se:latest
    container_name: jellyfin-se
    ports:
      - 7098:80
    restart: unless-stopped