version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: unpackerr_server_1
      APP_PORT: 5656
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: golift/unpackerr
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure